#pragma once

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define PLOOPY_DPI_OPTIONS {1400}
#define PLOOPY_DPI_DEFAULT 1
// #define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_DIVISOR_H 120.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 120.0

#define PLOOPY_DRAGSCROLL_MOMENTARY

#define POINTING_DEVICE_HIRES_SCROLL_ENABLE 0
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 15

// #define PLOOPY_DRAGSCROLL_DIVISOR_H 4.0
// #define PLOOPY_DRAGSCROLL_DIVISOR_V 4.0
